### ISSUE TITLE
Few issues when using this extension (linux shortcut & js error when run "Judge this email")

### ISSUE THREAD

**Issue by mics8128** [a-tak/auto-bucket#99]
Hi, 

I'm using Arch linux with KDE Plasma.
and using this extension with Thunderbird 68.10.0

have few issues.
1. shortcut is mac one, it is working but strange.
2. after I added classifications tags around 100 emails, I try to run "Judge this email" 10 similar emails, it didn't add any classification tag, and Statistics reset date always "NOW"
![圖片](https://user-images.githubusercontent.com/1339265/87306018-fb711c80-c549-11ea-8131-bac1277b6ba5.png)

**Comment by mics8128** [comment]
I try to run extension in debug mode and here is error message when I run "Judge this email"
![圖片](https://user-images.githubusercontent.com/1339265/87310850-1b580e80-c551-11ea-9d47-f0615659d7fc.png)

**Comment by a-tak** [comment]
Thank you for reporting. I'll think about what causes the error.

The reason why the shortcut is wrong may be that I have not set the shortcut for Linux. This will try to add the settings in the next version.

**Comment by a-tak** [comment]
> after I added classifications tags around 100 emails, I try to run "Judge this email" 10 similar emails, it didn't add any classification tag, and Statistics reset date always "NOW"


> I try to run extension in debug mode and here is error message when I run "Judge this email"
> 
> (background.ts line 535)
> ![圖片](https://user-images.githubusercontent.com/1339265/87310850-1b580e80-c551-11ea-9d47-f0615659d7fc.png)

I think the reason why an error occurs in the email judgment is that the tags used for classification have not been set from the extension settings first.

When you set the extension function, the item for learning is added to the right-click menu.

**Comment by a-tak** [comment]
I've heard that Chinese doesn't have spaces between words. Therefore, this extension may not work well.
Do you want Chinese email support?

**Comment by mics8128** [comment]
> I think the reason why an error occurs in the email judgment is that the tags used for classification have not been set from the extension settings first.
> 
> When you set the extension function, the item for learning is added to the right-click menu.

before I installed debug version, I had setup tags in settings, it may missing when I install debug version.
after add tags back to setting, it still have same error, maybe I have to trigger learn action?
![圖片](https://user-images.githubusercontent.com/1339265/87421324-5453ba00-c609-11ea-94a5-42beb4bbf910.png)

**Comment by mics8128** [comment]
> I've heard that Chinese doesn't have spaces between words. Therefore, this extension may not work well.
> Do you want Chinese email support?

hmm.. it maybe need some Chinese text segmentation to support Chinese emails, how to you handle this part for Japanese?

**Comment by a-tak** [comment]
> before I installed debug version, I had setup tags in settings, it may missing when I install debug version.
> after add tags back to setting, it still have same error, maybe I have to trigger learn action?

I'm not good at English, so I'm sorry my understanding was wrong.
This error occurs when you execute the mail judgment without learning even once.

**Comment by a-tak** [comment]
> > I've heard that Chinese doesn't have spaces between words. Therefore, this extension may not work well.
> > Do you want Chinese email support?
> 
> hmm.. it maybe need some Chinese text segmentation to support Chinese emails, how to you handle this part for Japanese?

This software uses "Tiny Segmenter" for Japanese division.
I think "Rakuten MA" can be used in Chinese.
https://github.com/rakuten-nlp/rakutenma/blob/master/README-ja.md

**Comment by a-tak** [comment]
> Hi,
> 
> I'm using Arch linux with KDE Plasma.
> and using this extension with Thunderbird 68.10.0
> 
> have few issues.
> 
> 1. shortcut is mac one, it is working but strange.
> 2. after I added classifications tags around 100 emails, I try to run "Judge this email" 10 similar emails, it didn't add any classification tag, and Statistics reset date always "NOW"
>    ![圖片](https://user-images.githubusercontent.com/1339265/87306018-fb711c80-c549-11ea-8131-bac1277b6ba5.png)

I installed Arch linux with KDE Plasma and tried a shortcut.
alt + shift + v are batting with Thunderbird shortcuts. I will change the Linux shortcuts in the next version.

**Comment by mics8128** [comment]
> I'm not good at English, so I'm sorry my understanding was wrong.
> This error occurs when you execute the mail judgment without learning even once.

It working perfect now, thanks for help. :+1: 

> This software uses "Tiny Segmenter" for Japanese division.
> I think "Rakuten MA" can be used in Chinese.
> https://github.com/rakuten-nlp/rakutenma/blob/master/README-ja.md

I look into my Chinese emails Judgment log
and word segmentation working, but not perfect. (10%~20% wrong)

Target text example: 
```
Fwd Google Ads 廣告 抵免 額已 套用 到您 帳戶 可用 來折 抵日 後的 廣告 支出 阿良 幫查 一下 是多 轉寄 郵件 寄件 Google Ads ads account noreply google com 日期 6月 上午 主旨 Google Ads 廣告 抵免 額已 套用 到您 帳戶 可用 來折 抵日 後的 廣告 支出 收件  gmail com 您的 客戶 ID 登入 有關 我們 瞭解 不管 是什 麼規 模的 公司 目前 都可 能面 COVID 帶來 種種 挑戰 而其 中有 許多 公司 一直 以來 都仰 Google Ads 協助 他們 接觸 客戶 因此 我們 發放 了一筆廣告 抵免 額給 符合 資格 帳戶 以示 支持 這筆 抵免 額將 可用 於折 抵本 年度 日後 廣告 支出 日過後 我們 會將 逾期 未使 用的 廣告 抵免 額從 帳戶 中移 您可 以在 Google Ads 帳戶 促銷 活動 頁面 上查 看廣 告抵 免額 方法 很簡 只要 登入 並點 擊該 頁面 頂端 工具 圖示 然後 帳單 下方 選取 促銷 活動 即可 若要進 一步 瞭解 這筆 廣告 抵免 請參 常見 問題 感謝 您長 久以來 合作 與支 祝您 平安 健康 Google Ads 團隊 敬上 您的 Google Ads 帳戶 有重 大異動 系統特此 發送 這封 電子 郵件 服務 公告 通知您 使用 這筆 廣告 抵免 額時 必須 遵守 您與 Google 之間 現行 適用 Google Ads 條款 及細 發放 廣告 抵免 額給 廣告 客戶 相關 事宜 Google 單方 面決定 不接 受申 廣告 抵免 額不 得出 交換 或以 其他 方式 轉移 from:x@gmail.com from:gmail.com to:x to:x
```

and I try to using "Rakuten MA", it only have Simplified Chinese training.
if I using Traditional Chinese will not working.

Simplified Chinese Result:
```
Ｇｏｏｇｌｅ [NR] | 　 [PU] | 的 [DEC] | 免费 [JJ] | 翻译 [NN] | 服务 [VV] | ， [PU] | 提供 [VV] | 中文 [NN] | 和 [CC] | 另外 [DT] | 上百 [CD] | 种 [M] | 语言 [NN] | 的 [DEG] | 互译 [NN] | 功能 [NN] | ， [PU] | 让 [VV] | 你 [PN] | 即时 [AD] | 翻译 [VV] | 字句 [NN] | 和 [CC] | 网页 [NN] | 内容 [NN] | 。 [PU]
```

Traditional Chinese Result:
```
Ｇ [] | ｏ [] | ｏ [] | ｇ [] | ｌ [] | ｅ [] | 　 [] | 的 [] | 免 [] | 費 [] | 翻 [] | 譯 [] | 服 [] | 務 [] | ， [] | 提 [] | 供 [] | 中 [] | 文 [] | 和 [] | 另 [] | 外 [] | 上 [] | 百 [] | 種 [] | 語 [] | 言 [] | 的 [] | 互 [] | 譯 [] | 功 [] | 能 [] | ， [] | 讓 [] | 你 [] | 即 [] | 時 [] | 翻 [] | 譯 [] | 字 [] | 句 [] | 和 [] | 網 [] | 頁 [] | 內 [] | 容 [] | 。 []
```

It also have to detect language before segmentation. (jp or zh)

If you want to improve this part, I think using language detect and different word segmentation will better,
otherwise you can keep using "Tiny Segmenter".

for Chinese word segmentation I suggest this one
https://github.com/yanyiwu/nodejieba
(this one also need add dictionary for Traditional Chinese support, but have more resource on internet)

and If you plan to make detect language and using different word segmentation, I can help for finish or test Chinese part.

**Comment by a-tak** [comment]
Thank you for trying "Rakuten MA".
I found it difficult to handle Chinese easily.
I want to try it when I have time.

**Comment by a-tak** [comment]
> Thank you for reporting. I'll think about what causes the error.
> 
> The reason why the shortcut is wrong may be that I have not set the shortcut for Linux. This will try to add the settings in the next version.

Apparently, if you change the shortcut settings from the extension's menu, I think it will work even with the current version.

![image](https://user-images.githubusercontent.com/4591907/87840291-dc6fe300-c8d9-11ea-8bb2-c20a2937d6da.png)
![image](https://user-images.githubusercontent.com/4591907/87840298-e98cd200-c8d9-11ea-9aa0-aeb047b3b611.png)
